#!/bin/sh

#############################################################################
#       Copyright (C) 2014 J. Miguel Farto <migeruhito@gmail.com>
#  Distributed under the terms of the GNU General Public License (GPL)
#  The full text of the GPL is available at:
#                  http://www.gnu.org/licenses/
#############################################################################

sage -python -m sagenb.run "$@"
